check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.34.1
  build-strategy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: graph-sync-job
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: thoth-station
  project-name: thoth-application
  image-name: graph-sync-job
  overlay-contextpath: graph-sync/overlays/test/imagestreamtag.yaml
