- project:
    check:
      jobs:
        - linters
    gate:
      jobs:
        - linters
    kebechet-auto-gate:
      jobs:
        - linters
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/graph-sync-job/webhooks/"
