apiVersion: v1
kind: Template
metadata:
  name: graph-sync-job-dependency-monkey
  annotations:
    description: "Thoth: Graph Sync Job for Dependency Monkey"
    openshift.io/display-name: "Thoth: Graph Sync Job Dependency Monkey"
    version: 0.6.0
    tags: thoth,ai-stacks,aistacks,graph-sync-job
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth's Graph Sync Job for Dependency Monkey on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: graph-sync-job-dependency-monkey
    app: thoth
    component: graph-sync
    graph-sync-type: dependency-monkey

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${THOTH_JOB_ID}
      labels:
        app: thoth
        component: graph-sync
        graph-sync-document-id: "${THOTH_SYNC_DOCUMENT_ID}"
        graph-sync-type: dependency-monkey
        mark: cleanup
        ttl: "1h"
    spec:
      template:
        metadata:
          labels:
            app: thoth
            component: graph-sync
            graph-sync-document-id: "${THOTH_SYNC_DOCUMENT_ID}"
            graph-sync-type: dependency-monkey
            mark: cleanup
            ttl: "1h"
        spec:
          containers:
            - image: graph-sync-job
              name: graph-sync
              env:
                - name: THOTH_ONLY_DEPENDENCY_MONKEY_DOCUMENTS
                  value: "1"
                - name: THOTH_SYNC_DOCUMENT_ID
                  value: "${THOTH_SYNC_DOCUMENT_ID}"
                - name: THOTH_FORCE_SYNC
                  value: "1"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: AMUN_API_URL
                  valueFrom:
                    configMapKeyRef:
                      key: amun-api-url
                      name: thoth
                - name: THOTH_SYNC_OBSERVATIONS
                  valueFrom:
                    configMapKeyRef:
                      key: sync-observations
                      name: thoth
                - name: THOTH_SYNC_INSPECTION_ONLY_GRAPH
                  value: "0"
                - name: THOTH_SYNC_INSPECTION_ONLY_CEPH
                  value: "0"
                - name: THOTH_S3_ENDPOINT_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-host
                      name: thoth
                - name: THOTH_CEPH_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-name
                      name: thoth
                - name: THOTH_CEPH_BUCKET_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-prefix
                      name: thoth
                - name: THOTH_CEPH_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-key-id
                - name: THOTH_CEPH_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-secret-key
                - name: THOTH_METRICS_PUSHGATEWAY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: metrics-pushgateway-url
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              livenessProbe:
                # Give sync 2 hours, if not finished, restart it.
                tcpSocket:
                  port: 80
                initialDelaySeconds: 7200
                failureThreshold: 1
                periodSeconds: 10
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: OnFailure

parameters:
  - name: THOTH_SYNC_DOCUMENT_ID
    required: true
    description: Document id to be synced.

  - name: THOTH_JOB_ID
    required: true
    description: Graph sync job identifier.
