apiVersion: v1
kind: Template
metadata:
  name: graph-sync-job-package-analyzer
  annotations:
    description: "Thoth: Graph Sync Job for package-analyzer documents"
    openshift.io/display-name: "Thoth: Graph Sync Job Package-Analyzer"
    version: 0.6.1
    tags: thoth,ai-stacks,aistacks,graph-sync-job
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth's Graph Sync Job for Package-Analyzers on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: graph-sync-job-package-analyzer
    app: thoth
    component: graph-sync
    graph-sync-type: package-analyzer

parameters:
  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Namespace the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - name: THOTH_SYNC_DOCUMENT_ID
    required: true
    description: Document id to be synced.

  - name: THOTH_JOB_ID
    required: true
    description: Graph sync job identifier.

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${THOTH_JOB_ID}"
      labels:
        app: thoth
        component: graph-sync
        graph-sync-document-id: "${THOTH_SYNC_DOCUMENT_ID}"
        graph-sync-type: package-analyzer
        # Clean this up after one hour.
        mark: cleanup
        ttl: "1h"
    spec:
      backoffLimit: 10
      template:
        metadata:
          labels:
            app: thoth
            component: graph-sync
            graph-sync-document-id: "${THOTH_SYNC_DOCUMENT_ID}"
            graph-sync-type: package-analyzer
            mark: cleanup
            ttl: "1h"
        spec:
          containers:
            - name: graph-sync
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/graph-sync-job:${IMAGE_STREAM_TAG}"
              env:
                - name: THOTH_ONLY_PACKAGE_ANALYZER_DOCUMENTS
                  value: "1"
                - name: THOTH_SYNC_DOCUMENT_ID
                  value: "${THOTH_SYNC_DOCUMENT_ID}"
                - name: THOTH_FORCE_SYNC
                  value: "1"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: THOTH_S3_ENDPOINT_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-host
                      name: thoth
                - name: THOTH_CEPH_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-name
                      name: thoth
                - name: THOTH_CEPH_BUCKET_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-prefix
                      name: thoth
                - name: THOTH_CEPH_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-key-id
                - name: THOTH_CEPH_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-secret-key
                - name: THOTH_METRICS_PUSHGATEWAY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: metrics-pushgateway-url
                - name: "THOTH_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
                - name: KNOWLEDGE_GRAPH_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: postgresql-host
                      name: thoth
                - name: KNOWLEDGE_GRAPH_PORT
                  value: "5432"
                - name: KNOWLEDGE_GRAPH_SSL_DISABLED
                  value: "1"
                - name: KNOWLEDGE_GRAPH_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-user
                - name: KNOWLEDGE_GRAPH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-password
                - name: KNOWLEDGE_GRAPH_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-name
              livenessProbe:
                # Give sync 2 hours, if not finished, restart it.
                tcpSocket:
                  port: 80
                initialDelaySeconds: 7200
                failureThreshold: 1
                periodSeconds: 10
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: OnFailure
